#fn_single_line = true
brace_style = "PreferSameLine"
comment_width = 120
enum_discrim_align_threshold = 30
format_doc_comments = true
format_strings = true
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 120
merge_imports = true
normalize_doc_attributes = true
reorder_impl_items = true
report_fixme = true
report_todo = true
struct_field_align_threshold = 30
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
